# Generated by Django 4.1.2 on 2022-11-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
